<?php
$config = Mage::getStoreConfig('mtdendadmin/static_config');
$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
?> 
<?php if ($config['static_mainbottom1']!=="") : ?>
<span class="span<?php echo $config['static_mainbottom1_cols'];?>"> 
<?php echo str_replace('{baseurl}', $url, $config['static_mainbottom1']); ?>
</span>
<?php endif; ?>

<?php if ($config['static_mainbottom2']!=="") : ?>
<span class="span<?php echo $config['static_mainbottom2_cols'];?>"> 
<?php echo str_replace('{baseurl}', $url, $config['static_mainbottom2']); ?>
</span>
<?php endif; ?>

<?php if ($config['static_mainbottom3']!=="") : ?>
<span class="span<?php echo $config['static_mainbottom3_cols'];?>">
<?php echo str_replace('{baseurl}', $url, $config['static_mainbottom3']); ?>
</span>
<?php endif; ?>

<?php if ($config['static_mainbottom4']!=="") : ?>
<span class="span<?php echo $config['static_mainbottom4_cols'];?>">
<?php echo str_replace('{baseurl}', $url, $config['static_mainbottom4']); ?>
</span>
<?php endif; ?>