<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Quantidade:') ?></label>
	
  <input type="button" class="reduced" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) && qty > 0 ) result.value--;return false;" />
   
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
  
  <input type="button" class="increase" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;">        <?php endif; ?>

  <a href="#parcelas" class="exibir-parcelamento"></a>
  <div class="parcelas" id="parcelas">
    <h2></h2>
    <ul>
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('parcelamento')->toHtml();?>
    </ul>
    <?php
        $c = 0;
        for($parcela = 1; $parcela <= 12; $parcela++)
        { 
            if($c++%6 == 0):      
                 echo '<ul class="valor-parcela">';
            endif; 

                switch($parcela){                                
                    case 7:
                        $juros = 1.0812;
                        break;
                    case 8:
                        $juros = 1.0916;
                        break;
                    case 9:
                        $juros = 1.1021;
                        break;
                    case 10:
                        $juros = 1.1127;
                        break;
                    case 11:
                        $juros = 1.1237;
                        break;
                    case 12:
                        $juros = 1.1340;
                        break;
                }                
                    if ($parcela<=6) {
                        if (($_product->getFinalPrice()/$parcela) >= 5) {
                            echo '<li class="valor-qtd-parcela"><b>'.$parcela.'x</b> '.Mage::helper('core')->currency($_product->getFinalPrice()/$parcela).' sem juros</li>';
                        }
                    }else{
                        if (($_product->getFinalPrice()/$parcela)*$juros >= 5) {
                            echo '<li class="valor-qtd-parcela"><b>'.$parcela.'x</b> '.Mage::helper('core')->currency(($_product->getFinalPrice()/$parcela) * $juros).' (juros de 1,99%)</li>';
                        }
                    }                        
            if ($c%6==0):
                echo '</ul>';
            endif;   
        }
    ?>
    <div class="boleto">
      <span class="a-vista">R$ <?php echo number_format($_product->getFinalPrice()*0.90,2,',','')?></span>
      <small><b>10% de desconto </b>à vista no boleto ou depósito bancário</small>
    </div>
  </div>

  <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><?php echo $buttonTitle ?></span></button>
  <?php if ($this->helper('wishlist')->isAllow()) : ?>
    <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
  <?php endif; ?>
        <span class="textrepuired"></span>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>


<script>
jQuery( document ).ready(function() {
  jQuery('.exibir-parcelamento').fancybox();
})
</script>