
<?php
function cut_string($string,$number){
        if(strlen($string) <= $number) {
            return $string;
        }
        else {	
            if(strpos($string," ",$number) > $number){
                $new_space = strpos($string," ",$number);
                $new_string = substr($string,0,$new_space)."...";
                return $new_string;
            }
            $new_string = substr($string,0,$number)."...";
            return $new_string;
        }
    }
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php if($this->getItems()->getSize()): ?>
  <div class="bloco-related">
    <div class="bloco-title">
		<div class="row-fluid show-grid">
			<div class="product-title">
				<span><?php echo $this->__('Related Products') ?></span>
			</div>
			<div class="pull-right span3">
				<div class="pagenav pull-right clearfix" >
					<span class="rprev" title="<?php echo $this->__('Previous') ?>"></span>
					<span class="rnext" title="<?php echo $this->__('Next') ?>"></span>
				</div>
			</div>			
		</div>
    </div>
    <div class="bloco-content">
    <div class="bloco-content-inner">
    <div class="row-fluid show-grid" id="bloco-related">
		<ul class="products-grid row-fluid show-grid">
			<?php $i = 0; foreach($this->getItems() as $_item): ?>
			<li class="item span3">
				<div class="item content">
				    <div class="item-inner">
					<div class="product-image">
						<div class="product-thumb">
							<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image">
								<?php echo $this->helper('mtdendadmin')->getLabel($_item);  ?>
								<span id="<?php echo $_item->getId();?>">
									<img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(260,300) ?>" width="260" height="300" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /> 
									<!-- <img src="<?php echo $this->getSkinUrl('images/flordosul/teste.png'); ?>"> -->
								</span>
							</a>		
		 
							<div class="mask" onclick="setLocation('<?php echo $_item->getProductUrl() ?>')">
								<h3 class="product-name">
									<a href="<?php echo $_item->getProductUrl() ?>">
										<span><?php echo $this->htmlEscape($_item->getName()) ?></span>
									</a>
								</h3>
	
							</div>

							<div class="box-hover">
		                        <h3 class="nome"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a> </h3>
		                        <div class="short-description">                             
		                            <?php echo cut_string($_helper->productAttribute($_item, nl2br($_item->getShortDescription()), 'short_description'),150); ?>
		                        </div>
		                        <div class="summary">

		                            <?php
		                            $storeId    = Mage::app()->getStore()->getId();

		                            $summaryData = Mage::getModel('review/review_summary')
		                            ->setStoreId($storeId)
		                                ->load($_item->getId());                   
		                        
		                            if($summaryData['reviews_count'] > 0){
		                            echo $this->getReviewsSummaryHtml($_item);
		                            }else{?>
		                             <div class="ratings"> 
		                                 <div class="rating-box">
		                                     <div style="width:0%" class="rating"></div>
		                                 </div>
		                            </div>
		                            <?php }?>
		                        </div>
	                    	</div> 
						</div>						
					</div>
					<div class="top-actions-inner">
						<span class="ajax-loading"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'/skin/frontend/default/mt_dend/images/loading.gif';?>"/></span>

							<?php echo $this->getPriceHtml($_item, true, '-related') ?>
							<div class="addtocart pull-left br">
								<?php if($_item->isSaleable()): ?>
								<?php if ( !($_item->getTypeInstance(true)->hasRequiredOptions($_item) || $_item->isGrouped()) ) { ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart grid" onclick="ajaxaddcart('<?php echo $this->getAddToCartUrl($_item) ?>',<?php echo $_item->getId() ?>)">
											<span><?php echo $this->__('Detalhes') ?></span>
									</button>								
								<?php } else { ?>									
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart grid" onclick="showOptions('<?php echo $_item->getId()?>')">
										<span><?php echo $this->__('Detalhes') ?></span>
									</button>
									<a href='<?php echo $this->getUrl('mtdendadmin/index/options',array('product_id'=>$_item->getId()));?>' class='fancybox' id='fancybox<?php echo $_item->getId()?>' style='display:none'>Add</a>
								<?php } ?>
								<?php else: ?>
								<p class="availability out-of-stock pull-left">
									<span class="out"><?php echo $this->__('Out of stock') ?></span>								
								</p>
								<?php endif; ?>
							</div>
							
							<div class="clearfix"></div>
							
							<!--<div class="wishlist pull-right br">
								<p>
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<a href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" data-id="<?php echo $_item->getId()?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
									<?php endif; ?>
								</p>
							</div>
							
							<div class="compare pull-left br">
								<p>
									<?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
										<a href="<?php echo $_compareUrl ?>" data-id="<?php echo $_item->getId()?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
									<?php endif; ?>
								</p>
							</div>
							
							<div class="detail pull-left">
								<button type="button" title="<?php echo $this->__('Detail') ?>" class="button btn-detail" onclick="setLocation('<?php echo $_item->getProductUrl() ?>')"><span><span><?php echo $this->__('Detail') ?></span></span></button>
							</div>-->
						
					</div>
					</div>
				</div>
			</li>
			<?php if (++$i > 3): 
				break;
			endif ?>
			<?php endforeach ?>
		</ul>
	</div>
</div>
<script type="text/javascript">decorateList('bloco-related', 'none-recursive')</script>
</div>
<script type="text/javascript">
    //<![CDATA[

    // $mtkb(function() {
    // 	$mtkb(".mini-products-list").jCarouselLite({
    //     btnPrev: ".rprev",
    //     btnNext: ".rnext",
    //     vertical: false,
    //     hoverPause:true,
    //     visible: 4,
    //     auto: 0,
    //     speed: 1000
    //   });
    // });

	jQuery(document).ready(function(){
		jQuery("#bloco-related .item" ).hover(function(){
	        jQuery(this).find(".box-hover").css("display", "block").addClass("animated bounceIn");
	    }, function(){
	        jQuery(this).find(".box-hover").css("display", "none").removeClass("bounceIn");
	    });
	});


    $$('.related-checkbox').each(function(elem){
      Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
      if (relatedProductsCheckFlag == false) {
        $$('.related-checkbox').each(function(elem){
          elem.checked = true;
        });
        relatedProductsCheckFlag = true;
        txt.innerHTML="<?php echo $this->__('unselect all') ?>";
      } else {
        $$('.related-checkbox').each(function(elem){
          elem.checked = false;
        });
        relatedProductsCheckFlag = false;
        txt.innerHTML="<?php echo $this->__('select all') ?>";
      }
      addRelatedToProduct();
    }

    function addRelatedToProduct(){
      var checkboxes = $$('.related-checkbox');
      var values = [];
      for(var i=0;i<checkboxes.length;i++){
        if(checkboxes[i].checked) values.push(checkboxes[i].value);
      }
      if($('related-products-field')){
        $('related-products-field').value = values.join(',');
      }
    }
    //]]>
    </script>
  </div>
<?php endif ?>
