<?php
    $otherconfig = Mage::getStoreConfig('mtdendadmin/otherconfig');
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
  
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view ">
    <div class="product-essential row-fluid show-grid">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
		<input type="hidden" name="related_product" id="related-products-field" value="" />

        <div class="product-img-box span6 no-margin">
        	<?php echo $this->helper('mtdendadmin')->getLabel($_product);  ?>
            <?php echo $this->getChildHtml('media') ?>
        </div>        
        
        <div class="product-shop span6">
            
            	<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
            	<input type="hidden" id="optioncheck" name="optioncheck" value="0"/>
            	<?php }else{?>
            	<input type="hidden" id="optioncheck" name="optioncheck" value="1"/>
            	<?php }?>
                <span class="name-brand-view"><?php echo $_product->getData('brand') ?></span>
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                <?php echo $this->getChildHtml('addto') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>

                <!-- frete gratis -->
                <?php if ($_product['frete_gratis']): ?>
                    <?php echo '<div class="frete-gratis"></div>' ?>
                <?php endif ?>  

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
                
                <!-- atributos - cor - tamanho  -->
                <?php Mage::register('color_product', $_product); ?>
                <?php echo $this->getChildHtml('color'); ?>

                <?php echo $this->getChildHtml('product.static') ?> 
                
                <!-- <br style="clear:both;" /> -->

                <?php if ($_product->getTypeId() !== 'bundle') { ?>
                    <div class="avista">
                        ou <span>R$<?php echo number_format($_product->getFinalPrice()*0.97 ,2,',','.'); ?></span> à vista
                    </div>
                <?php } ?>
                
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            
                <?php echo $this->getTierPriceHtml() ?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <h3><?php echo $this->__('Detalhes do Produto') ?></h2>
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif;?>
            
            <?php if ($_product['tabela_medidas']): ?>
                <div class="medidas">
                    <h3>Medidas da peça</h3>
                     <?php echo $_product->getData('tabela_medidas') ?> 
                </div>
            <?php endif; ?>
            <ul class="share">
                <span>Compartilhe!</span>                
                <li><div class="fb-like" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div></li>
                <li><div class="g-plusone" data-size="medium" data-annotation="none"></div></li>
                <li><a data-pin-config="above" href="//pinterest.com/pin/create/button/?url=<?php echo $this->getBaseUrl() . $_product->getUrlPath(); ?>&media=<?php echo $this->getBaseUrl() . 'media/catalog/product' . $_product->getImage() ?>&description=<?php echo $_product->getName() . ' na Móveis pra Você'; ?>" title="Mande este produto para o pinterest" data-pin-do="buttonPin" class="share_pinterest"  onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"></a></li>
                <li><a href="https://twitter.com/share?url=<?php echo $this->getBaseUrl() . $_product->getUrlPath(); ?>" title="Tuíte sobre este produto" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;" class="share_twitter">twitter</a></li>


               
            </ul>      
             <!-- scripts social -->
                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>

                <script type="text/javascript">
                  window.___gcfg = {lang: 'pt-BR'};

                  (function() {
                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                    po.src = 'https://apis.google.com/js/platform.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                  })();
                </script>
                <!-- fim scripts social -->      

                

            <?php echo $this->getChildHtml('extra_buttons') ?>

			
            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
            
            
            <div class="clearer"></div>
            
            </div>

    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
		<?php /* if($otherconfig['enabled_ajax']){?>
        productAddToCartForm.submit = function(button, url) {  
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                if (!url) {
    				url = $mtkb('#product_addtocart_form').attr('action');
    			}
				if($mtkb('body').find('.viewquickloook').val()>0){
   				 	try {
	                    this.form.submit();
	                } catch (e) {
		                
	                }
        		}else{  
					url = url.replace("checkout/cart","mtdendadmin/index"); // New Code 
					var data = $mtkb('#product_addtocart_form').serialize(); 
					data += '&isAjax=1';  
					try {
						if($mtkb('#optioncheck').val()==0){ 
							if($mtkb('#qty').val()==0){ 
								$mtkb("span.textrepuired").html('<?php echo $this->__('The quantity not zero!');?>');
							}else{
								$mtkb("span.textrepuired").html('');
								$mtkb('.cart-loading').show();
								$mtkb('.cart').hide();
								$mtkb.ajax( {
									url : url,
									dataType : 'json',
									type : 'post',
									data : data,
									success : function(data) { 
										parent.setAjaxData(data,true);
										$mtkb('.cart-loading').hide();
										$mtkb('.cart').show();
										parent.showMessage(data.message);
                	                	parent.ajaxReload(data,true); 
										if (button && button != 'undefined') {
											button.disabled = false;
										}
									}
								});
							}  
						}else{
							$mtkb('.cart-loading').show();
		    				$mtkb('.cart').hide();
							$mtkb.ajax( {
								url : url,
								dataType : 'json',
								type : 'post',
								data : data,
								success : function(data) { 
									parent.setAjaxData(data,true);
									$mtkb('.cart-loading').hide();
									parent.removeLoading();
									$mtkb('.cart').show();
									parent.showMessage(data.message);
            	               	 	parent.ajaxReload(data,true); 
								}
							});
						}
					} catch (e) {
					}
				}
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

            }
        }.bind(productAddToCartForm);
		<?php }else{ */ ?>
		productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);
		<?php /* } */ ?>
        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>
    <!-- sua escolha -->
    <?php if ($_product['tabela_medidas']): ?>
        <div class="sua-escolha">
            <h3 class="title-view">Conheça mais sobre sua escolha!</h3>
            <div class="video">
                <?php echo $_product->getData('sua_escolha') ?>
            </div>
        </div>
    <?php endif ; ?>
    <!-- //fim sua escolha -->
    <!-- guia de medidas -->
    <?php if ($_product['guia_medidas']): ?>
        <div class="guia-medidas">
            <h3 class="title-view">Guia de medidas</h3>
            <div class="guia-content">
                <?php echo $_helper->productAttribute($_product, nl2br($_product->getGuiaMedidas()), 'guia_medidas') ?>
            </div>
        </div>
    <?php endif ; ?>
    <!-- //fim guia de medidas -->
    <!-- Entrega e troca -->
    <?php if ($_product['entrega_troca']): ?>
        <div class="entrega-troca">
            <h3 class="title-view">Entrega rápida e troca fácil</h3>
            <div class="content-entrega">
                <?php echo $_product->getData('entrega_troca') ?>
            </div>
        </div>
    <?php endif ; ?>
    <!-- //fim entrega e troca -->

    <div class="product-collateral">
        <?php echo $this->getChildHtml('info_tabs') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('related_products') ?>
</div>
