<?php $marcas = $this->getAllMarcas(); ?>

<?php if (count($marcas) > 0): ?>

	<div class="marcas-home marcas-carousel hidden-phone visible-desktop">
		<h2>Compre por Marca</h2>
		<div class="marcas-carousel-content">
			<span class="button-bg button-bg-left"></span>
			<ul id="carousel-marcas-home" class="jcarousel-skin-marcas-home">

				<?php foreach ($marcas as $key => $marca): ?>
				<?php if ($marca['url']): ?>
					<li>

						<?php if (strpos($marca['image'], 'http://') === false): ?>
							<?php $image = $this->getBaseUrl().'media/'. $marca['image'] ?>
						<?php else: ?>
							<?php $image = $marca['image']; ?>
						<?php endif ?>
						<a target="_blank" href="<?php echo $marca['url'] ?>"><img src="<?php echo $image ?>" title="<?php echo $marca['label'] ?>" width="90" height="55"></a>
					</li>		
				<?php endif ?>
				<?php endforeach ?>
			</ul>
			<span class="button-bg button-bg-right"></span>
		</div>

		<script type="text/javascript">
			jQuery(document).ready(function() {
				jQuery('#carousel-marcas-home').jcarousel({
					visible: 5
				});
			});
		</script>

	</div>

<?php endif ?>
