<?php
/*------------------------------------------------------------------------
# APL Solutions and Vision Co., LTD
# ------------------------------------------------------------------------
# Copyright (C) 2008-2010 APL Solutions and Vision Co., LTD. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: APL Solutions and Vision Co., LTD
# Websites: http://www.joomlavision.com/ - http://www.magentheme.com/
-------------------------------------------------------------------------*/
?>
<?php
$config = Mage::getStoreConfig('mtdendadmin/mtdendadmin_appearance');
$_direct = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/direction');
$_items = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/items');
$_thumb_w = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/width');
$_thumb_h = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/height');
$_show_control = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/control');
$_auto_scroll = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/auto_scroll');
$_speed = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/speed');
$_top_vert = $_items*$_thumb_h + $_items*8 + 24;
$_left_hor = $_items*$_thumb_w + $_items*9 + 14;
$_count_thumb = 0;
$_left_ctr = ($_thumb_w/2) - 20;
$_top_ctr = ($_thumb_h-20)/2;
$_zoom_w = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/width_z');
$_zoom_h = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/height_z');
$_lightbox_w = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/width_lbox');
$_lightbox_h = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/height_lbox');
$_enabled_zoom = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/enabled_zoom');
$_enabled_scroller = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/enabled_scroller');
$_enabled_lightbox = Mage::getStoreConfig('mtdendadmin/thumbnailscroller/enabled_lightbox');
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?> 
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
    <?php
    $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
    //echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    <?php if($_enabled_zoom) {?> 
    <?php if($config['theme_responsive']){?>
    <?php if($_enabled_lightbox){?>
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_lightbox_w, $_lightbox_h); ?>" class = "mt-a-lighbox visible-desktop" rel="lightbox[rotation]"></a>
    <?php }?>
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(); ?>" class = "cloud-zoom visible-desktop" id="mt-zoom1" style="position: relative; display: block;" rel="adjustX:10, adjustY:-2, zoomWidth:<?php echo $_zoom_w; ?>, zoomHeight:<?php echo $_zoom_h;?>, showTitle: true, titleOpacity: 0.01">
        <img class="imgbox"  src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(); ?>" alt='' title="" />
    </a>
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(); ?>" class = "hidden-desktop" id="mt-zoom1" style="position: relative; display: block;">
        <img class="imgbox"  src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(); ?>" alt='' title="" />
    </a>
    <?php }else{?>
    <?php if($_enabled_lightbox){?>
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_lightbox_w, $_lightbox_h); ?>" class = "mt-a-lighbox" rel="lightbox[rotation]"></a>
    <?php }?>
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(); ?>" class = "cloud-zoom" id="mt-zoom1" style="position: relative; display: block;" rel="adjustX:10, adjustY:-2, zoomWidth:<?php echo $_zoom_w; ?>, zoomHeight:<?php echo $_zoom_h;?>, showTitle: true, titleOpacity: 0.01">
        <img class="imgbox"  src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(); ?>" alt='' title="" />
    </a>
    <?php }?>
    <?php } else {
    	echo $_helper->productAttribute($_product, $_img, 'image');
	}?>
</p> 
<?php else: ?>
<p class="product-image">
    <?php
    $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
    echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
 
<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="mt-more-images">
    <div class="more-views"> 
        <div class="mt-more-views">
            <ul id="mt-thumbscroller" class="mt-thumbscroller">
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php $_count_thumb ++;?>
                <li style="height:140px;">
                    <?php if($_enabled_zoom) {?>
                    <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(1200,1200); ?>" class="cloud-zoom-gallery" title="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>"
                       rel="useZoom: 'mt-zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(); ?>'">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_thumb_w-4,$_thumb_h-4); ?>" width="<?php echo $_thumb_w-4; ?>" height = "<?php echo $_thumb_h-4; ?>" alt = ""/></a>
                    <?php } else { ?>
                    <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumb_w-4,$_thumb_h-4); ?>" width="<?php echo $_thumb_w-4;?>" height="<?php echo $_thumb_h-4; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                    <?php } ?>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
    $mtkb(document).ready(function() {
        $mtkb('#mt-thumbscroller').jcarousel({
            auto: 1,
            
            <?php if (($_count_thumb > $_items) && ($_show_control) && ($_enabled_scroller)) {?>
            buttonNextHTML: '<span class="next hidden-phone hidden-tablet" title="<?php echo $this->__('Next') ?>">&nbsp;</span>',
            buttonPrevHTML: '<span class="prev hidden-phone hidden-tablet" title="<?php echo $this->__('Previos') ?>">&nbsp;</span>',
            <?php } ?>
            scroll: 1,
            initCallback: mycarousel_initCallback
        });
        <?php if($_enabled_zoom) {?>
            $mtkb(".mt-more-views li a").click(function(){
                $mtkb("a.mt-a-lighbox").attr("href",$mtkb(this).attr("title"));
            });
        <?php } ?>
    });
    function mycarousel_initCallback(carousel)
    { 
        carousel.buttonNext.bind('click', function() {
            carousel.startAuto(0);
        }); 
        carousel.buttonPrev.bind('click', function() {
            carousel.startAuto(0);
        }); 
        carousel.clip.hover(function() {
            carousel.stopAuto();
        }, function() {
            carousel.startAuto();
        });
    };
</script>
<?php endif; ?>