<?php if($this->getCurrencyCount()>1): ?>
        <label for="select-language">Currency: </label>
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <?php $active = ($_code==$this->getCurrentCurrencyCode()) ? '_active':''; ?>
            <a href="<?php echo $this->helper('directory/url')->getSwitchCurrencyUrl() . 'currency/' . $_code; ?>" title="Set <?php echo $_code ?> as your chosen currency">
            <img src="<?php echo Mage::getBaseUrl() . 'media/currency/' . $_code . $active;?>.png" alt="Set <?php echo $_code ?> as your chosen currency" />
            </a>
        <?php endforeach; ?>
<script type="text/javascript">
//<![CDATA[
function changeCurrency(sObject){
    if(sObject.value){
        setLocation('<?php echo $this->helper('directory/url')->getSwitchCurrencyUrl() ?>currency/'+sObject.value);
    }
}
//]]>
</script>
<?php else : ?>
&nbsp;
<?php endif; ?>