<?php $id = Mage::registry('current_category')->getId() ?>
<?php $marcas = $this->getListaMarcas($id); ?>

<?php if (count($marcas) > 0): ?>

	<div class="marcas-category marcas-carousel">
	
		<h2>Compre por Marca</h2>
		<div class="marcas-carousel-content">
			<span class="button-bg button-bg-left"></span>
			<ul id="carousel-marcas-category" class="jcarousel-skin-marcas-category">
				<?php foreach ($marcas as $key => $marca): ?>
					<li>
						<?php $image = $marca['image']; ?>
						<?php if (strpos($marca['image'], 'http://') !== 0): ?>
							<?php $image = $this->getBaseUrl().'media/'. $marca['image'] ?>
						<?php endif ?>
						<a target="_blank" href="<?php echo $marca['url'] ?>"><img src="<?php echo $image ?>" title="<?php echo $marca['label'] ?>" width="90" height="55"></a>
					</li>
				<?php endforeach ?>
			</ul>
			<span class="button-bg button-bg-right"></span>
		</div>
	</div>

	<script type="text/javascript">
		jQuery(document).ready(function($) {
			jQuery('#carousel-marcas-category').jcarousel({
				visible: 5
			});
		});
	</script>
<?php endif ?>
