<?php $marcas = $this->getAllMarcas(); ?>

<?php if (count($marcas) > 0): ?>

	<div class="marcas-home marcas-carousel hidden-phone visible-desktop">
		<div class="product-title">
			<span>Marcas</span>
		</div>
		<div class="pagenave pull-right">
            <button title="Anterior" onclick="jQuery('.jcarousel-prev').click();" id="pscroll-prev">&lt;</button>
            <button title="Próximo" onclick="jQuery('.jcarousel-next').click();" id="pscroll-next">&gt;</button>
        </div>
		<div class="marcas-carousel-content">
			<ul id="carousel-marcas-home" class="jcarousel-skin-marcas-home">

				<?php foreach ($marcas as $key => $marca): ?>
				<?php if ($marca['url']): ?>
					<li>
						<?php if (strpos($marca['image'], 'http://') === false): ?>
							<?php $image = $this->getBaseUrl().'media/'. $marca['image'] ?>
						<?php else: ?>
							<?php $image = $marca['image']; ?>
						<?php endif ?>
						<a target="_blank" href="<?php echo $marca['url'] ?>"><img src="<?php echo $image ?>" title="<?php echo $marca['label'] ?>"></a>
					</li>		
				<?php endif ?>
				<?php endforeach ?>
			</ul>
		</div>

		<script type="text/javascript">
			jQuery(document).ready(function() {
				jQuery('#carousel-marcas-home').jcarousel({
					visible: 6
				});
			});
		</script>

	</div>

<?php endif ?>
