<?php

/*------------------------------------------------------------------------
# APL Solutions and Vision Co., LTD
# ------------------------------------------------------------------------
# Copyright (C) 2008-2011 APL Solutions and Vision Co., LTD. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: APL Solutions and Vision Co., LTD
# Websites: http://www.joomlavision.com/ - http://www.9magentothemes.com/
-------------------------------------------------------------------------*/


$config = Mage::getStoreConfig('mtdendadmin/mtdendadmin_appearance');
$otherconfig = Mage::getStoreConfig('mtdendadmin/otherconfig');
$actionhover = $this->getConfig('hoverpause');
if($actionhover>0) $hoverpause = 'true'; else $hoverpause = 'false';
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php if($this->getConfig('enabled')): ?> <!-- start enable module -->
<?php
//width, height of slider
    $item = $this->getConfig('items');
// width, height of thumbnail
    $w = $this->getConfig('width');
    $h = $this->getConfig('height');
    $mainWidth = $this->getConfig('main_width');
    $mainHeight = $this->getConfig('main_height');
    $pagenavWidth = $item*$this->getConfig('width_item');
    $wslider = $w * $item;
    $hslider = $h;
    $this->getListProducts();
    $_productCollection=$this->getProductCollection();
    if(count($_productCollection)>0){
        ?>
    <div class="mt_productscroller container">
        <?php if($this->getConfig('title')){?>
        <div class="block-title">
            <div class="row-fluid show-grid">
                <div class="product-title">                   
                    <span>
                        <?php echo $this->getConfig('title')?>
                    </span>                  
                </div>
                <div class="mtpagenave pull-right span1">
                    <div class="pagenave pull-right clearfix" style="width:auto !important;">
                        <button id="pscroll-prev" class="prev" title="<?php echo $this->__('Previous') ?>"><</button>
                        <button id="pscroll-next" class="next" title="<?php echo $this->__('Next') ?>">></button>
                    </div>
                </div>
            </div>
        </div>
        <?php }?>
        <div id="mt_productscroller" class="scroller-slider " style="width: <?php echo $mainWidth;?>px; height: <?php echo $mainHeight;?>px;">
            <ul style="margin: 0pt; padding: 0pt; position: relative; list-style-type: none; z-index: 1;">
                <?php $i = 0; foreach ($_productCollection as $_product): ?>
                <li class="items-slider loading" style="overflow: hidden; float: left; width: <?php echo $this->getConfig('width_item');?>px; height: <?php echo $mainHeight;?>px;">
                <div class="catpanel ">
                        <div class="content">
                            <div class="product-image">
                                <div class="product-thumb">
                                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image" style="position: relative; display: block;">
                                        <?php echo $this->helper('mtdendadmin')->getLabel($_product);  ?> 
                                            <!-- <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/magenthemes/mt_dend/js/productsscroller/timthumb/timthumb.php?src='.$this->helper('catalog/image')->init($_product, 'small_image').'&amp;h='.$h.' &amp;w='.$w; ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /> -->

                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize("$w"); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                    </a>
                                </div>
                                <div class="mask" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                                    <h3 class="product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                    </h3>
                                    <!--<?php //if ($_product->getShortDescription()):?>
										<div class="short-description">								
											<?php //echo cut_string($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'),150) ?>
										</div>
									<?php //endif;?>-->
                                </div>

                                    <div class="box-hover">
                                        <h3 class="nome"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a> </h3>
                                        <div class="short-description">                             
                                            <?php echo cut_string($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'),150); ?>
                                        </div>
                                        <div class="summary">

                                            <?php
                                            $storeId    = Mage::app()->getStore()->getId();

                                            $summaryData = Mage::getModel('review/review_summary')
                                            ->setStoreId($storeId)
                                                ->load($_product->getId());                   
                                        
                                            if($summaryData['reviews_count'] > 0){
                                            echo $this->getReviewsSummaryHtml($_product);
                                            }else{?>
                                             <div class="ratings"> 
                                                 <div class="rating-box">
                                                     <div style="width:0%" class="rating"></div>
                                                 </div>
                                            </div>
                                            <?php }?>

                                        </div>
                                    </div>        
                            </div>
                            <div class="top-actions-inner">
                                <span class="ajax-loading"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'/skin/frontend/default/mt_dend/images/loading.gif';?>"/></span>
                                <!--price-->
									<?php if($this->getConfig('price')): ?>
									<?php echo $this->getPriceHtml($_product, true) ?>
									<?php endif; ?>
                                <!--Other-->
                                <div class="mt-actions clearfix">
                                <div class="addtocart br">
                                    <?php if($_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->__('Comprar') ?>" class="button btn-detail" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                                                <span><?php echo $this->__('Comprar') ?></span>
                                            </button>
                                        <?php //else: ?>
                                            <!-- <p class="availability out-of-stock">
                                                <span class="label" style="display:none;"><?php //echo $this->__('Availability:') ?></span>
                                                <span class="out"><?php //echo $this->__('Out of stock') ?></span>
                                            </p> -->
                                        <?php endif; ?>
                                </div>
								<div class="clearfix"></div>
								<?php if( $this->getConfig('addtowishlist') ){?>
                                <div class="wishlist pull-left br">
                                    <p> 
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId(); ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>">
                                            <?php echo $this->__('Add to Wishlist') ?>
                                        </a>
                                        <?php endif; ?>
                                    </p>
                                </div>
                                <?php } ?>
                                <?php if( $this->getConfig('addtocompare') ){?>
                                <div class="compare pull-left br">
                                    <p>
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <a href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId(); ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>">
                                            <?php echo $this->__('Add to Compare') ?>
                                        </a>
                                        <?php endif; ?> 
                                    </p>
                                </div>
                                <?php }?> 
                                <?php if ($this->getConfig('detail') ):?>
										<div class="detail pull-left">
											<button type="button" title="<?php echo $this->__('Detail') ?>" class="button btn-detail" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
												<span><?php echo $this->__('Detail') ?></span>
											</button>
										</div>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- lancamento -->
	                <?php 
	                	if($_product['lancamento']){
                       		echo '<div class="flag-lancamento"></div>'; 
                    	} 
                    ?>

                    <!-- desconto -->
                     <?php if ($_product->isSaleable()): ?>

                            <?php if ($_product->getFinalPrice() != $_product->getPrice()): ?>
                                <?php
                                    $preco_inicial = $_product->getPrice();
                                    $preco_final = $_product->getFinalPrice();

                                    $porcentagem = (($preco_inicial - $preco_final)/$preco_inicial)*100;

                                    if ($porcentagem > 0){
                                        $discounts['porcentagem'] =	$porcentagem;
                                    }

                                ?>
                                <span class="flag-desconto">-<?php echo ceil ($discounts['porcentagem']); ?>% </span>

                            <?php endif ?>

                        <?php endif ?>

                        <!-- promocao -->
	                <?php 
	                	if($_product['promocao']){
                       		echo '<div class="flag-promocao"></div>'; 
                    	} 
                    ?>
                </li>
                <?php $i++;endforeach ?>
            </ul>
        </div>
    </div>
    <script type="text/javascript">
        $mtkb(document).ready(function(){
            var w = $mtkb(".container").width();
            var mainw = $mtkb(".scroller-slider").width();
            var navresize = function(){
                w = $mtkb(".container").width();
                if(w <= mainw){
                    $mtkb(".scroller-slider").css("width", w);
                }else{
                    $mtkb(".scroller-slider").css("width", mainw);
                }
            }
            navresize();
            $mtkb(window).resize(function(){
                navresize();
            });
        });
        $mtkb(document).ready(function(){
            $mtkb(function() {
                $mtkb("#mt_productscroller").jCarouselLite({
                    btnNext: "#pscroll-next",
                    btnPrev: "#pscroll-prev",
                    visible: <?php echo $item;?>,
                    auto: <?php echo $this->getConfig('auto') ?>,
                    scroll: <?php echo $this->getConfig('items_scroll') ?>,
                    easing: "swing",
                    speed: <?php echo $this->getConfig('animation') ?>,
                    caption_color	: 'black',
                    caption_bgcolor	: '#D6DEE2',
                    hoverPause: <?php echo $hoverpause;?>,
                    overlay_bgcolor 	: '',
                    border		: '',
                    showcaption	: false
                });
            });
        });
    </script>
    <?php }?>
<?php endif; ?> 