<?php
/******************************************************
 * @package MT Slideshow module for Magento 1.4.x.x, Magento 1.5.x.x and Magento 1.6.x.x
 * @version 2.0.0
 * @author http://www.magentheme.com
 * @copyright (C) 2011- MagenTheme.Com
 * @license PHP files are GNU/GPL
*******************************************************/
$slide_id = $this->getRequest()->getParam('id');
$model  = Mage::getModel('mtslideshow/mtslideshow')->load($slide_id);
?>
<?php $_block = $this; ?>
<style>
    .mt-listimages select.file-animate, .mt-listimages select.link-animate, .mt-listimages select.title-animate, .mt-listimages select.desc-animate {
        display: none;
    }
</style>
<div id="<?php echo $_block->getHtmlId() ?>" class="mt-listimages">
    <div class="grid">
        <table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid_mtslideshow" width="100%">
            <col width="120" />
            <col width="260" />
            <col width="260" />
            <col width="160" />           
            <col width="50" />
            <col width="50" />
            <thead>
                <tr class="headings">
                    <th><?php echo Mage::helper('mtslideshow')->__('Image') ?></th>
                    <th><?php echo Mage::helper('mtslideshow')->__('Link') ?></th>                    
                    <th><?php echo Mage::helper('mtslideshow')->__('Title') ?></th>
                    <th><?php echo Mage::helper('mtslideshow')->__('Description') ?></th>
                    <th><?php echo Mage::helper('mtslideshow')->__('Order') ?></th>
                    <th><?php echo Mage::helper('mtslideshow')->__('Disable') ?></th>
                    <th class="last"><?php echo Mage::helper('mtslideshow')->__('Remove') ?></th>
                </tr>
            </thead>
            <tbody id="<?php echo $_block->getHtmlId() ?>_list">
                <tr id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display">
                    <td class="cell-image" width="13%">
                        <div class="place-holder" onmouseover="<?php echo $_block->getJsObjectName(); ?>.loadImage('__file__')">
                            <span><?php echo Mage::helper('mtslideshow')->__('Roll Over for preview') ?></span>
                        </div>
                        <img src="<?php echo $this->getSkinUrl('images/spacer.gif')?>" width="100" style="display:none;" alt="" />
                        <select class="file-animate" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" style="width: 72%; margin-top: 10px; <?php if($model->getStyle()=='mtcooslider'){?>display:block;<?php }?>">
                            <option value="random">random</option>
                            <option value="barDown">barDown</option>
                            <option value="barDownReverse">barDownReverse</option>
                            <option value="barDownSymmetry">barDownSymmetry</option>
                            <option value="barUp">barUp</option>
                            <option value="barUpDown">barUpDown</option>
                            <option value="barUpDownSymmetry">barUpDownSymmetry</option>
                            <option value="blind">blind</option>
                            <option value="blindHorizontal">blindHorizontal</option>
                            <option value="bounce">bounce</option>
                            <option value="bounceIn">bounceIn</option>
                            <option value="bounceInDown">bounceInDown</option>
                            <option value="bounceInLeft">bounceInLeft</option>
                            <option value="bounceInRight">bounceInRight</option>
                            <option value="bounceInUp">bounceInUp</option>
                            <option value="boxFadeIn">boxFadeIn</option>
                            <option value="boxInOut">boxInOut</option>
                            <option value="boxRain">boxRain</option>
                            <option value="boxRainGrow">boxRainGrow</option>
                            <option value="boxRainGrowReverse">boxRainGrowReverse</option>
                            <option value="boxRainReverse">boxRainReverse</option>
                            <option value="boxRandom">boxRandom</option>
                            <option value="boxSpiral">boxSpiral</option>
                            <option value="boxSpiralReverse">boxSpiralReverse</option>
                            <option value="boxTopBottom">boxTopBottom</option>
                            <option value="circleFadeIn">circleFadeIn</option>
                            <option value="circleFadeOut">circleFadeOut</option>
                            <option value="cut">cut</option>
                            <option value="fadeIn">fadeIn</option>
                            <option value="fadeInDown">fadeInDown</option>
                            <option value="fadeInDownBig">fadeInDownBig</option>
                            <option value="fadeInLeft">fadeInLeft</option>
                            <option value="fadeInLeftBig">fadeInLeftBig</option>
                            <option value="fadeInRight">fadeInRight</option>
                            <option value="fadeInRightBig">fadeInRightBig</option>
                            <option value="fadeInUp">fadeInUp</option>
                            <option value="fadeInUpBig">fadeInUpBig</option>
                            <option value="flash">flash</option>
                            <option value="flip">flip</option>
                            <option value="flipInX">flipInX</option>
                            <option value="flipInY">flipInY</option>
                            <option value="glass">glass</option>
                            <option value="glassReverse">glassReverse</option>
                            <option value="lightSpeedIn">lightSpeedIn</option>
                            <option value="pulse">pulse</option>
                            <option value="rollIn">rollIn</option>
                            <option value="rotateIn">rotateIn</option>
                            <option value="rotateInDownLeft">rotateInDownLeft</option>
                            <option value="rotateInDownRight">rotateInDownRight</option>
                            <option value="rotateInUpLeft">rotateInUpLeft</option>
                            <option value="rotateInUpRight">rotateInUpRight</option>
                            <option value="shake">shake</option>
                            <option value="slab">slab</option>
                            <option value="slideDown">slideDown</option>
                            <option value="slideLeft">slideLeft</option>
                            <option value="slideRight">slideRight</option>
                            <option value="slideUp">slideUp</option>
                            <option value="swap">swap</option>
                            <option value="swing">swing</option>
                            <option value="tada">tada</option>
                            <option value="wiggle">wiggle</option>
                            <option value="wobble">wobble</option>
                        </select>
                    </td>
                    <td class="cell-link a-center" width="20%">
                        <input type="text" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                        <select class="link-animate" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" style="width: 72%; margin: 12px 0 0 12px; <?php if($model->getStyle()=='mtcooslider'){?>display:block;<?php }?>">
                            <option value="random">random</option>
                            <option value="bounce">bounce</option>
                            <option value="bounceIn">bounceIn</option>
                            <option value="bounceInDown">bounceInDown</option>
                            <option value="bounceInLeft">bounceInLeft</option>
                            <option value="bounceInRight">bounceInRight</option>
                            <option value="bounceInUp">bounceInUp</option>
                            <option value="circleFadeIn">circleFadeIn</option>
                            <option value="circleFadeOut">circleFadeOut</option>
                            <option value="fadeIn">fadeIn</option>
                            <option value="fadeInDown">fadeInDown</option>
                            <option value="fadeInDownBig">fadeInDownBig</option>
                            <option value="fadeInLeft">fadeInLeft</option>
                            <option value="fadeInLeftBig">fadeInLeftBig</option>
                            <option value="fadeInRight">fadeInRight</option>
                            <option value="fadeInRightBig">fadeInRightBig</option>
                            <option value="fadeInUp">fadeInUp</option>
                            <option value="fadeInUpBig">fadeInUpBig</option>
                            <option value="flash">flash</option>
                            <option value="flip">flip</option>
                            <option value="flipInX">flipInX</option>
                            <option value="flipInY">flipInY</option>
                            <option value="lightSpeedIn">lightSpeedIn</option>
                            <option value="pulse">pulse</option>
                            <option value="rollIn">rollIn</option>
                            <option value="rotateIn">rotateIn</option>
                            <option value="rotateInDownLeft">rotateInDownLeft</option>
                            <option value="rotateInDownRight">rotateInDownRight</option>
                            <option value="rotateInUpLeft">rotateInUpLeft</option>
                            <option value="rotateInUpRight">rotateInUpRight</option>
                            <option value="shake">shake</option>
                            <option value="swing">swing</option>
                            <option value="tada">tada</option>
                            <option value="wiggle">wiggle</option>
                            <option value="wobble">wobble</option>
                        </select>
                    </td>
                    <td class="cell-title a-center"width="25%">
                        <input type="text" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                        <select class="title-animate" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" style="width: 72%; margin: 12px 0 0 12px; <?php if($model->getStyle()=='mtcooslider'){?>display:block;<?php }?>">
                            <option value="random">random</option>
                            <option value="bounce">bounce</option>
                            <option value="bounceIn">bounceIn</option>
                            <option value="bounceInDown">bounceInDown</option>
                            <option value="bounceInLeft">bounceInLeft</option>
                            <option value="bounceInRight">bounceInRight</option>
                            <option value="bounceInUp">bounceInUp</option>
                            <option value="circleFadeIn">circleFadeIn</option>
                            <option value="circleFadeOut">circleFadeOut</option>
                            <option value="fadeIn">fadeIn</option>
                            <option value="fadeInDown">fadeInDown</option>
                            <option value="fadeInDownBig">fadeInDownBig</option>
                            <option value="fadeInLeft">fadeInLeft</option>
                            <option value="fadeInLeftBig">fadeInLeftBig</option>
                            <option value="fadeInRight">fadeInRight</option>
                            <option value="fadeInRightBig">fadeInRightBig</option>
                            <option value="fadeInUp">fadeInUp</option>
                            <option value="fadeInUpBig">fadeInUpBig</option>
                            <option value="flash">flash</option>
                            <option value="flip">flip</option>
                            <option value="flipInX">flipInX</option>
                            <option value="flipInY">flipInY</option>
                            <option value="lightSpeedIn">lightSpeedIn</option>
                            <option value="pulse">pulse</option>
                            <option value="rollIn">rollIn</option>
                            <option value="rotateIn">rotateIn</option>
                            <option value="rotateInDownLeft">rotateInDownLeft</option>
                            <option value="rotateInDownRight">rotateInDownRight</option>
                            <option value="rotateInUpLeft">rotateInUpLeft</option>
                            <option value="rotateInUpRight">rotateInUpRight</option>
                            <option value="shake">shake</option>
                            <option value="swing">swing</option>
                            <option value="tada">tada</option>
                            <option value="wiggle">wiggle</option>
                            <option value="wobble">wobble</option>
                        </select>
                    </td>
                    <td class="cell-description a-center"width="30%">
                        <textarea style="width:95%" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')"></textarea>
                        <select class="desc-animate" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" style="width: 72%; margin: 5px 0 5px 12px; <?php if($model->getStyle()=='mtcooslider'){?>display:block;<?php }?>">
                            <option value="random">random</option>
                            <option value="bounce">bounce</option>
                            <option value="bounceIn">bounceIn</option>
                            <option value="bounceInDown">bounceInDown</option>
                            <option value="bounceInLeft">bounceInLeft</option>
                            <option value="bounceInRight">bounceInRight</option>
                            <option value="bounceInUp">bounceInUp</option>
                            <option value="circleFadeIn">circleFadeIn</option>
                            <option value="circleFadeOut">circleFadeOut</option>
                            <option value="fadeIn">fadeIn</option>
                            <option value="fadeInDown">fadeInDown</option>
                            <option value="fadeInDownBig">fadeInDownBig</option>
                            <option value="fadeInLeft">fadeInLeft</option>
                            <option value="fadeInLeftBig">fadeInLeftBig</option>
                            <option value="fadeInRight">fadeInRight</option>
                            <option value="fadeInRightBig">fadeInRightBig</option>
                            <option value="fadeInUp">fadeInUp</option>
                            <option value="fadeInUpBig">fadeInUpBig</option>
                            <option value="flash">flash</option>
                            <option value="flip">flip</option>
                            <option value="flipInX">flipInX</option>
                            <option value="flipInY">flipInY</option>
                            <option value="lightSpeedIn">lightSpeedIn</option>
                            <option value="pulse">pulse</option>
                            <option value="rollIn">rollIn</option>
                            <option value="rotateIn">rotateIn</option>
                            <option value="rotateInDownLeft">rotateInDownLeft</option>
                            <option value="rotateInDownRight">rotateInDownRight</option>
                            <option value="rotateInUpLeft">rotateInUpLeft</option>
                            <option value="rotateInUpRight">rotateInUpRight</option>
                            <option value="shake">shake</option>
                            <option value="swing">swing</option>
                            <option value="tada">tada</option>
                            <option value="wiggle">wiggle</option>
                            <option value="wobble">wobble</option>
                        </select>
                    </td>
                    <td class="cell-order a-center"width="5%">
                        <input type="text" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                    <td class="cell-disable a-center"width="5%">
                        <input type="checkbox" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                    <td class="cell-remove a-center last">
                        <input type="checkbox" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                    </td>
                </tr>

                <tr id="<?php echo $_block->getHtmlId() ?>-image-0">
                    <td class="cell-image"><?php echo Mage::helper('catalog')->__('No image') ?></td>
                    <td class="cell-link"><input type="hidden" />&nbsp;</td>                    
                    <td class="cell-title"><input type="hidden" />&nbsp;</td>
                    <td class="cell-description"><input type="hidden" />&nbsp;</td>
                    <td class="cell-order"><input type="hidden" />&nbsp;</td>
                    <td class="cell-disable"><input type="hidden" />&nbsp;</td>
                    <td class="cell-remove"><input type="hidden" />&nbsp;</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="100" class="last" style="padding:8px">
                        <?php echo $_block->getUploaderHtml() ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="images" value="<?php echo $_block->htmlEscape($_block->getImagesJson()) ?>" />
<input type="hidden" id="smece_save" name="[smece]" value="smece" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="[values]" value="<?php echo $_block->htmlEscape($_block->getImagesValuesJson()) ?>" />
<script type="text/javascript">
    //<![CDATA[
    var <?php echo $_block->getJsObjectName(); ?> = new SlideShow.Gallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getUploader()->getJsObjectName() ?>, <?php echo $_block->getImageTypesJson() ?>);
    //]]>
</script>