<?php 
/*------------------------------------------------------------------------
# APL Solutions and Vision Co., LTD
# ------------------------------------------------------------------------
# Copyright (C) 2008-2010 APL Solutions and Vision Co., LTD. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: APL Solutions and Vision Co., LTD
# Websites: http://www.joomlavision.com/ - http://www.magentheme.com/
-------------------------------------------------------------------------*/ 	
$config = Mage::getStoreConfig('mtdendadmin/mtdendadmin_appearance');
?>
<?php 
	$title=Mage::getStoreConfig('mtdendadmin/smartmenu/title');
	$style=Mage::getStoreConfig('mtdendadmin/smartmenu/menustyle');
	$event=Mage::getStoreConfig('mtdendadmin/smartmenu/event');  
?>
<?php if($config['theme_responsive']>0){?>
<div class="mt-drillmenu hidden-desktop span12">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<span class="brand"><?php echo $this->__('Categorias');?></span>
				<div class="nav-collapse collapse"> 
					<script type="text/javascript"> 
						$mtkb(document).ready(function() {
							$mtkb("#mt_accordionmenu").mtAccordionMenu({
								accordion:true,
								speed: 500,
								closedSign: 'collapse',
								openedSign: 'expand',
								mouseType: 0,
								easing: 'easeInOutBack'
							});
						}); 
					</script>
					<ul id="mt_accordionmenu" class="nav-accordion">
						<li><a href="<?php echo $this->getBaseUrl(); ?>"><?php echo $this->__('Home'); ?></a></li>
						<?php foreach ($this->getStoreCategories() as $_category): ?>
							<?php echo $this->drawItem($_category) ?>
						<?php endforeach ?>
					</ul> 
				</div>
			</div>
		</div>
	</div>
</div> 
<?php }?>