<?php
$config = Mage::getStoreConfig('mtdendadmin/static_config');
$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
?>
<?php if ($config['static_footer1']!=="") : ?>
<span class="span<?php echo $config['static_footer1_cols'];?>">
<?php echo str_replace('{baseurl}', $url, $config['static_footer1']); ?>
</span>
<?php endif; ?>

<?php if ($config['static_footer2']!=="") : ?>
<span class="span<?php echo $config['static_footer2_cols'];?>"> 
<?php echo str_replace('{baseurl}', $url, $config['static_footer2']); ?>
</span>
<?php endif; ?>

<!--<?php if ($config['static_footer3']!=="") : ?>
<span class="span<?php echo $config['static_footer3_cols'];?>"> 
<?php echo str_replace('{baseurl}', $url, $config['static_footer3']); ?>
</span>
<?php endif; ?>

<?php if ($config['static_footer4']!=="") : ?>
<span class="span<?php echo $config['static_footer4_cols'];?>"> 
<?php echo str_replace('{baseurl}', $url, $config['static_footer4']); ?>
</span>
<?php endif; ?>-->